/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: maxdragonn (https://sketchfab.com/maxdragon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/1982-sony-betacam-2278728ec0a2456b8793210d24f4dd79
title: 1982 Sony Betacam
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'
import gsap from "gsap";

export default function Camera(props) {
  const group = useRef();

  useEffect(() => {
    gsap.to(group.current.rotation,{
      y:5,
      scrollTrigger: {
        trigger:".Productos",
        scrub: 1, 
        start: 'top top',
        end: '100%'
      }
    })
  })

  const { nodes, materials } = useGLTF('Models/Camera/scene.gltf');
  return (
    <group ref={group} {...props} dispose={null} scale={[0.1,0.1,0.1]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[4.08, 1.01, 5.9]} rotation={[-0.27, 0.6, 1.93]} scale={[0.1, 0.1, 0.1]} />
        <mesh material={materials.camcorder} geometry={nodes.camcorder_0.geometry} />
        <mesh material={materials.cam_lens} geometry={nodes.camcorder_1.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('Models/Camera/scene.gltf')
