/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF,useAnimations } from '@react-three/drei'



export default function DJI(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('Models/Dji/DJI.gltf')
  const { actions } = useAnimations(animations, group)


  useEffect(() => {
      console.log(actions); 
  },[]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]} />
      <group position={[0, 0, -0.08]} rotation={[Math.PI / 2, 0, 0.01]} scale={[0.02, 0.02, 0.02]}>
        <group name="f_low" position={[0, -2.57, 8.47]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="a_low" position={[0, -0.72, -16.93]}>
            <group name="c_low" position={[0, -16.1, 22.92]}>
              <group name="CENTRE" position={[0, 8.01, -0.6]} rotation={[0, 0, 0]}>
                <group position={[0, -15.58, 0.6]}>
                  <mesh material={materials.SYSTEME_MECHANIC} geometry={nodes.CENTRE_SYSTEME_MECHANIC_0.geometry} />
                </group>
              </group>
              <mesh material={materials.SYSTEME_MECHANIC} geometry={nodes.c_low_SYSTEME_MECHANIC_0.geometry} />
            </group>
            <group name="VIS_CD" position={[-0.97, -8.34, 17.68]}>
              <group position={[4.72, 10.74, 7.72]}>
                <mesh material={materials.BRAS} geometry={nodes.VIS_CD_BRAS_0.geometry} />
              </group>
            </group>
            <group position={[0, 9.19, 19.5]}>
              <mesh material={materials.material} geometry={nodes.b_low_SSD_0.geometry} />
            </group>
            <group position={[0, 9.19, 19.5]}>
              <mesh material={materials.BLOCK_BATTERIE} geometry={nodes.a_low_BLOCK_BATTERIE_0.geometry} />
            </group>
            <group position={[0.97, -8.34, 17.68]}>
              <group position={[2.77, 10.74, 7.72]}>
                <mesh material={materials.BRAS} geometry={nodes.VIS_CG2_BRAS_0.geometry} />
              </group>
            </group>
          </group>
          <group name="i_low" position={[0, -15.48, 22.45]}>
            <group name="CAM_C" position={[0.02, -6.72, 0.97]}>
              <group name="CAM_BACK" position={[0, -16.28, -14.63]}>
                <group name="j_low" position={[-11.27, 0, 17.47]}>
                  <group position={[11.25, 16.2, -17.48]}>
                    <mesh material={materials.LENTILLE} geometry={nodes.lentille_LENTILLE_0.geometry} />
                  </group>
                  <group position={[11.25, 16.2, -17.48]}>
                    <mesh material={materials.CAMERA} geometry={nodes.j_low_CAMERA_0.geometry} />
                  </group>
                </group>
                <group position={[-0.02, 16.2, -0.01]}>
                  <mesh material={materials.CAMERA} geometry={nodes.CAM_BACK_CAMERA_0.geometry} />
                </group>
              </group>
              <group position={[-0.02, -0.09, -14.63]}>
                <mesh material={materials.CAMERA} geometry={nodes.CAM_C_CAMERA_0.geometry} />
              </group>
            </group>
            <group position={[0, -6.03, -13.66]}>
              <mesh material={materials.STABILISATEUR} geometry={nodes.i_low_STABILISATEUR_0.geometry} />
            </group>
          </group>
          <group position={[0, -1.76, -19.38]}>
            <group position={[0, 10.22, 21.95]}>
              <mesh material={materials.BATTERIE} geometry={nodes.e_low_BATTERIE_0.geometry} />
            </group>
          </group>
          <group position={[0, 6.9, 19.47]} rotation={[0, 0, -Math.PI / 2]} scale={[0.14, 0.14, 0.14]}>
            <group position={[62.91, 0, 1.27]}>
              <mesh material={materials.BLOCK_AVANT} geometry={nodes.h_low_BLOCK_AVANT_0.geometry} />
            </group>
          </group>
          <group position={[0, 8.47, 2.57]}>
            <mesh material={materials.COQUE} geometry={nodes.f_low_COQUE_0.geometry} />
          </group>
        </group>
        <group name="Object018" position={[2.58, 2.8, 3.86]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Object013" position={[0.03, -3.77, 0]}>
            <group name="Object012" position={[-0.03, 0.05, 0]}>
              <group name="Object010" position={[1.84, 1.34, 0]}>
                <group name="Object011" position={[-0.01, -0.02, 0]}>
                  <group name="BRAD_G" position={[1.83, 1.11, 0.07]} rotation={[0, 0.03, -1.07]}>
                    <group name="Object020" position={[-0.8, 1.45, 6.76]} rotation={[0.21, 0.02, 1.16]}>
                      <group position={[-1.7, -3.09, -3.73]}>
                        <mesh material={materials.BRAS} geometry={nodes.Object020_BRAS_0.geometry} />
                      </group>
                    </group>
                    <group name="PIN_G" position={[32.06, 17.56, -14.72]}>
                      <group name="PIED1" position={[4.36, 2.45, -0.45]} rotation={[0.03, -0.01, 1.07]}>
                        <group name="BOUCLE_G" position={[0, -0.01, -9.07]} rotation={[0, 0, 0.78]}>
                          <group name="VIS_G" position={[0.18, -7.34, 6.08]}>
                            <group name="PETIT_BRAS_G" position={[-0.06, 0.03, -0.47]} rotation={[-0.1, 0.23, -1.55]}>
                              <group position={[-39.1, -14.2, 21.61]}>
                                <mesh material={materials.BRAS} geometry={nodes.PETIT_BRAS_G_BRAS_0.geometry} />
                              </group>
                            </group>
                            <group position={[-39.16, -14.19, 21.15]}>
                              <mesh material={materials.BRAS} geometry={nodes.VIS_G_BRAS_0.geometry} />
                            </group>
                          </group>
                          <group position={[-42.69, -15.62, 23.05]}>
                            <mesh material={materials.PIEDS} geometry={nodes.BOUCLE_G_PIEDS_0.geometry} />
                          </group>
                        </group>
                        <group name="MOTOR1" position={[0.03, 3.34, 52.33]} rotation={[-0.07, 0, 0]}>
                          <group position={[-0.05, 14.75, -94.58]} rotation={[0.09, 0, 0]}>
                            <mesh material={materials.HELICES} geometry={nodes.MOTOR1_HELICES_0.geometry} />
                          </group>
                          <group position={[-0.05, 4.32, -0.18]} rotation={[0.09, 0, 0]}>
                            <group position={[0, 2.19, -94.95]}>
                              <mesh material={materials.HELICES} geometry={nodes.PROPELLER1_low_HELICES_0.geometry} />
                            </group>
                          </group>
                        </group>
                        <group name="MOTOR4" position={[0.07, 3.36, -43.59]} rotation={[0.09, 0, 0]}>
                          <group position={[-0.09, 6.46, -0.11]} rotation={[-0.08, 0, 0]}>
                            <mesh material={materials.HELICES} geometry={nodes.MOTOR4_HELICES_0.geometry} />
                          </group>
                          <group position={[0.12, 4.31, -0.16]} rotation={[2.63, 1.55, -2.63]}>
                            <group position={[-0.24, 2.15, -0.26]} rotation={[-0.09, 0, 0]}>
                              <mesh material={materials.HELICES} geometry={nodes.PROPELLER4_low_HELICES_0.geometry} />
                            </group>
                          </group>
                        </group>
                        <group position={[-42.69, -15.62, 13.98]}>
                          <mesh material={materials.PIEDS} geometry={nodes.PIED1_PIEDS_0.geometry} />
                        </group>
                      </group>
                      <group position={[-34.59, -19.16, 17.7]}>
                        <mesh material={materials.BRAS} geometry={nodes.PIN_G_BRAS_0.geometry} />
                      </group>
                    </group>
                    <group name="VIS_CG" position={[4.15, -1.44, -0.11]} rotation={[0.01, 0, 0.73]}>
                      <group name="Object003" position={[0, 0, 0]} rotation={[0.01, 0, 0.73]}>
                        <group name="Object002" position={[-4.58, -3.48, 0.12]} rotation={[-0.01, 0, 0.37]}>
                          <group name="Object001" position={[-0.01, 0, 0]} rotation={[-0.01, 0, 0.37]}>
                            <group name="Object008" position={[-3.37, 0.22, -0.07]}>
                              <group position={[-5.82, -15.17, 0.61]}>
                                <mesh
                                  material={materials.SYSTEME_MECHANIC}
                                  geometry={nodes.Object008_SYSTEME_MECHANIC_0.geometry}
                                />
                              </group>
                            </group>
                            <group position={[-5.81, -15.22, 0.57]}>
                              <mesh
                                material={materials.SYSTEME_MECHANIC}
                                geometry={nodes.Object001_SYSTEME_MECHANIC_0.geometry}
                              />
                            </group>
                          </group>
                          <group position={[-5.82, -15.17, 0.61]}>
                            <mesh
                              material={materials.SYSTEME_MECHANIC}
                              geometry={nodes.Object002_SYSTEME_MECHANIC_0.geometry}
                            />
                          </group>
                        </group>
                        <group position={[-10.4, -18.65, 0.66]}>
                          <mesh
                            material={materials.SYSTEME_MECHANIC}
                            geometry={nodes.Object003_SYSTEME_MECHANIC_0.geometry}
                          />
                        </group>
                      </group>
                      <group position={[-6.64, -0.15, 3.07]}>
                        <mesh material={materials.BRAS} geometry={nodes.VIS_CG_BRAS_0.geometry} />
                      </group>
                    </group>
                    <group position={[-2.51, -1.61, 3]}>
                      <mesh material={materials.BRAS} geometry={nodes.BRAD_G_BRAS_0.geometry} />
                    </group>
                  </group>
                  <group position={[-4.41, -19.02, 0.62]}>
                    <mesh
                      material={materials.SYSTEME_MECHANIC}
                      geometry={nodes.Object011_SYSTEME_MECHANIC_0.geometry}
                    />
                  </group>
                </group>
                <group position={[-4.42, -19.04, 0.62]}>
                  <mesh material={materials.SYSTEME_MECHANIC} geometry={nodes.Object010_SYSTEME_MECHANIC_0.geometry} />
                </group>
              </group>
              <group position={[-2.58, -17.71, 0.62]}>
                <mesh material={materials.SYSTEME_MECHANIC} geometry={nodes.Object012_SYSTEME_MECHANIC_0.geometry} />
              </group>
            </group>
            <group position={[-2.61, -17.65, 0.62]}>
              <mesh material={materials.SYSTEME_MECHANIC} geometry={nodes.Object013_SYSTEME_MECHANIC_0.geometry} />
            </group>
          </group>
          <group position={[-2.58, -17.71, 0.62]}>
            <mesh material={materials.SYSTEME_MECHANIC} geometry={nodes.Object018_SYSTEME_MECHANIC_0.geometry} />
          </group>
        </group>
        <group name="Object019" position={[-2.58, 2.8, 3.86]} rotation={[-1.57, 0, 0]}>
          <group name="Object014" position={[-0.03, -3.77, 0]}>
            <group name="Object015" position={[0.03, 0.05, 0]}>
              <group name="Object016" position={[-1.86, 1.3, 0]}>
                <group name="Object017" position={[0.03, 0.01, 0]}>
                  <group name="BRAS_D" position={[-1.83, 1.11, 0.07]} rotation={[0, -0.02, 1.05]}>
                    <group name="k_low" position={[0.8, 1.45, 6.76]} rotation={[0.19, -0.02, -1.14]}>
                      <group position={[9.19, -3.09, -3.73]}>
                        <mesh material={materials.BRAS} geometry={nodes.k_low_BRAS_0.geometry} />
                      </group>
                    </group>
                    <group name="PIN_D" position={[-32.06, 17.56, -14.72]}>
                      <group name="PIED2" position={[-4.36, 2.45, -0.45]} rotation={[0.02, 0.01, -1.05]}>
                        <group name="BOUCLE_D001" position={[0, -0.01, -9.08]} rotation={[0, 0, -0.64]}>
                          <group name="VIS_D" position={[-0.18, -7.34, 6.08]}>
                            <group name="PETIT_BRAS_D" position={[0.06, 0.03, -0.47]} rotation={[-0.11, -0.22, 1.52]}>
                              <group position={[46.59, -14.2, 21.61]}>
                                <mesh material={materials.BRAS} geometry={nodes.PETIT_BRAS_D_BRAS_0.geometry} />
                              </group>
                            </group>
                            <group position={[0, 0, 0]}>
                              <mesh material={materials.BRAS} geometry={nodes.VIS_D_BRAS_0.geometry} />
                            </group>
                          </group>
                          <group position={[42.69, -15.62, 23.05]}>
                            <mesh material={materials.PIEDS} geometry={nodes.BOUCLE_D001_PIEDS_0.geometry} />
                          </group>
                        </group>
                        <group name="MOTOR2" position={[-0.03, 3.34, 52.34]} rotation={[-0.09, 0, 0]}>
                          <group position={[85.4, 14.93, -94.55]} rotation={[0.09, 0, 0]}>
                            <mesh material={materials.HELICES} geometry={nodes.MOTOR2_HELICES_0.geometry} />
                          </group>
                          <group position={[0.05, 4.72, -0.15]} rotation={[0.09, 0, 0]}>
                            <group position={[85.35, 1.78, -94.94]}>
                              <mesh material={materials.HELICES} geometry={nodes.PROPELLER2_low_HELICES_0.geometry} />
                            </group>
                          </group>
                        </group>
                        <group name="MOTOR3" position={[-0.08, 3.16, -43.59]} rotation={[0.06, 0, -0.05]}>
                          <group position={[85.44, 6.66, -0.14]} rotation={[-0.09, 0, 0]}>
                            <mesh material={materials.HELICES} geometry={nodes.MOTOR3_HELICES_0.geometry} />
                          </group>
                          <group position={[-0.16, 4.41, 0.06]} rotation={[Math.PI, -1.45, Math.PI]}>
                            <group position={[85.6, 2.25, -0.21]} rotation={[-0.09, 0, 0]}>
                              <mesh material={materials.HELICES} geometry={nodes.PROPELLER3_low_HELICES_0.geometry} />
                            </group>
                          </group>
                        </group>
                        <group position={[42.69, -15.62, 13.98]}>
                          <mesh material={materials.PIEDS} geometry={nodes.PIED2_PIEDS_0.geometry} />
                        </group>
                      </group>
                      <group position={[42.08, -19.16, 17.7]}>
                        <mesh material={materials.BRAS} geometry={nodes.PIN_D_BRAS_0.geometry} />
                      </group>
                    </group>
                    <group name="VIZ_CD" position={[-4.16, -1.47, -0.07]} rotation={[0.01, 0, -0.72]}>
                      <group name="Object005" position={[0, 0, 0]} rotation={[0.01, 0, -0.72]}>
                        <group name="Object006" position={[4.6, -3.49, 0.08]} rotation={[-0.01, 0, -0.37]}>
                          <group name="Object004" position={[0, 0, 0]} rotation={[-0.01, 0, -0.37]}>
                            <group name="Object009" position={[3.38, 0.27, -0.07]} rotation={[0, 0, 0]}>
                              <group position={[-5.82, -15.17, 0.61]}>
                                <mesh
                                  material={materials.SYSTEME_MECHANIC}
                                  geometry={nodes.Object009_SYSTEME_MECHANIC_0.geometry}
                                />
                              </group>
                            </group>
                            <group position={[5.82, -15.17, 0.61]}>
                              <mesh
                                material={materials.SYSTEME_MECHANIC}
                                geometry={nodes.Object004_SYSTEME_MECHANIC_0.geometry}
                              />
                            </group>
                          </group>
                          <group position={[5.82, -15.17, 0.61]}>
                            <mesh
                              material={materials.SYSTEME_MECHANIC}
                              geometry={nodes.Object006_SYSTEME_MECHANIC_0.geometry}
                            />
                          </group>
                        </group>
                        <group position={[10.42, -18.67, 0.69]}>
                          <mesh
                            material={materials.SYSTEME_MECHANIC}
                            geometry={nodes.Object005_SYSTEME_MECHANIC_0.geometry}
                          />
                        </group>
                      </group>
                      <group position={[14.13, -0.15, 3.07]}>
                        <mesh material={materials.BRAS} geometry={nodes.VIZ_CD_BRAS_0.geometry} />
                      </group>
                    </group>
                    <group position={[10, -1.61, 3]}>
                      <mesh material={materials.BRAS} geometry={nodes.BRAS_D_BRAS_0.geometry} />
                    </group>
                  </group>
                  <group position={[4.41, -19.02, 0.62]}>
                    <mesh
                      material={materials.SYSTEME_MECHANIC}
                      geometry={nodes.Object017_SYSTEME_MECHANIC_0.geometry}
                    />
                  </group>
                </group>
                <group position={[4.44, -19.01, 0.62]}>
                  <mesh material={materials.SYSTEME_MECHANIC} geometry={nodes.Object016_SYSTEME_MECHANIC_0.geometry} />
                </group>
              </group>
              <group position={[2.58, -17.71, 0.62]}>
                <mesh material={materials.SYSTEME_MECHANIC} geometry={nodes.Object015_SYSTEME_MECHANIC_0.geometry} />
              </group>
            </group>
            <group position={[2.61, -17.65, 0.62]}>
              <mesh material={materials.SYSTEME_MECHANIC} geometry={nodes.Object014_SYSTEME_MECHANIC_0.geometry} />
            </group>
          </group>
          <group position={[2.58, -17.71, 0.62]}>
            <mesh material={materials.SYSTEME_MECHANIC} geometry={nodes.Object019_SYSTEME_MECHANIC_0.geometry} />
          </group>
        </group>
        <group position={[0, 0, 61.69]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.7, 0.76, 1.7]}>
          <mesh material={materials.PISTE} geometry={nodes.PISTE_PISTE_0.geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('Models/Dji/DJI.gltf')
