/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF,useAnimations  } from '@react-three/drei'



export default function DroneR(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('Models/Drone/Drone.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[0.01, 0.01, 0.01]}>
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh
              material={materials.material_0}
              geometry={nodes.Mesh_0_1.geometry}
              skeleton={nodes.Mesh_0_1.skeleton}
            />
            <skinnedMesh
              material={materials.material_2}
              geometry={nodes.Mesh_0_2.geometry}
              skeleton={nodes.Mesh_0_2.skeleton}
            />
            <skinnedMesh
              material={materials.material_3}
              geometry={nodes.Mesh_0_3.geometry}
              skeleton={nodes.Mesh_0_3.skeleton}
            />
            <skinnedMesh
              material={materials.material_8}
              geometry={nodes.Mesh_0_4.geometry}
              skeleton={nodes.Mesh_0_4.skeleton}
            />
            <skinnedMesh
              material={materials.material_10}
              geometry={nodes.Mesh_0_5.geometry}
              skeleton={nodes.Mesh_0_5.skeleton}
            />
            <skinnedMesh
              material={materials.material_11}
              geometry={nodes.Mesh_0_6.geometry}
              skeleton={nodes.Mesh_0_6.skeleton}
            />
            <skinnedMesh
              material={materials.material_12}
              geometry={nodes.Mesh_0_7.geometry}
              skeleton={nodes.Mesh_0_7.skeleton}
            />
            <skinnedMesh
              material={materials.material_13}
              geometry={nodes.Mesh_0_8.geometry}
              skeleton={nodes.Mesh_0_8.skeleton}
            />
            <skinnedMesh
              material={materials.material_21}
              geometry={nodes.Mesh_0_9.geometry}
              skeleton={nodes.Mesh_0_9.skeleton}
            />
            <skinnedMesh
              material={materials.material_22}
              geometry={nodes.Mesh_0_10.geometry}
              skeleton={nodes.Mesh_0_10.skeleton}
            />
            <skinnedMesh
              material={materials.material_23}
              geometry={nodes.Mesh_0_11.geometry}
              skeleton={nodes.Mesh_0_11.skeleton}
            />
            <skinnedMesh
              material={materials.material_24}
              geometry={nodes.Mesh_0_12.geometry}
              skeleton={nodes.Mesh_0_12.skeleton}
            />
            <skinnedMesh
              material={materials.material_29}
              geometry={nodes.Mesh_0_13.geometry}
              skeleton={nodes.Mesh_0_13.skeleton}
            />
            <skinnedMesh
              material={materials.material_33}
              geometry={nodes.Mesh_0_14.geometry}
              skeleton={nodes.Mesh_0_14.skeleton}
            />
            <skinnedMesh
              material={materials.material_34}
              geometry={nodes.Mesh_0_15.geometry}
              skeleton={nodes.Mesh_0_15.skeleton}
            />
            <skinnedMesh
              material={materials.material_35}
              geometry={nodes.Mesh_0_16.geometry}
              skeleton={nodes.Mesh_0_16.skeleton}
            />
            <skinnedMesh
              material={materials.material_36}
              geometry={nodes.Mesh_0_17.geometry}
              skeleton={nodes.Mesh_0_17.skeleton}
            />
            <skinnedMesh
              material={materials.material_37}
              geometry={nodes.Mesh_0_18.geometry}
              skeleton={nodes.Mesh_0_18.skeleton}
            />
            <skinnedMesh
              material={materials.material_39}
              geometry={nodes.Mesh_0_19.geometry}
              skeleton={nodes.Mesh_0_19.skeleton}
            />
            <skinnedMesh
              material={materials.material_40}
              geometry={nodes.Mesh_0_20.geometry}
              skeleton={nodes.Mesh_0_20.skeleton}
            />
            <skinnedMesh
              material={materials.material_42}
              geometry={nodes.Mesh_0_21.geometry}
              skeleton={nodes.Mesh_0_21.skeleton}
            />
            <skinnedMesh
              material={materials.material_43}
              geometry={nodes.Mesh_0_22.geometry}
              skeleton={nodes.Mesh_0_22.skeleton}
            />
            <skinnedMesh
              material={materials.material_45}
              geometry={nodes.Mesh_0_23.geometry}
              skeleton={nodes.Mesh_0_23.skeleton}
            />
            <skinnedMesh
              material={materials.material_46}
              geometry={nodes.Mesh_0_24.geometry}
              skeleton={nodes.Mesh_0_24.skeleton}
            />
            <skinnedMesh
              material={materials.material_48}
              geometry={nodes.Mesh_0_25.geometry}
              skeleton={nodes.Mesh_0_25.skeleton}
            />
            <skinnedMesh
              material={materials.material_57}
              geometry={nodes.Mesh_0_26.geometry}
              skeleton={nodes.Mesh_0_26.skeleton}
            />
            <skinnedMesh
              material={materials.material_58}
              geometry={nodes.Mesh_0_27.geometry}
              skeleton={nodes.Mesh_0_27.skeleton}
            />
            <skinnedMesh
              material={materials.material_59}
              geometry={nodes.Mesh_0_28.geometry}
              skeleton={nodes.Mesh_0_28.skeleton}
            />
            <skinnedMesh
              material={materials.material_60}
              geometry={nodes.Mesh_0_29.geometry}
              skeleton={nodes.Mesh_0_29.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('Models/Drone/Drone.glb')
