/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: LaVADraGoN (https://sketchfab.com/lavadragon)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/buster-drone-294e79652f494130ad2ab00a13fdbafd
title: Buster Drone
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/core/useGLTF'



export default function Drone(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('Models/Drone/scene.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -100, -5]} />
          <group position={[0, 0.12, -12.91]} rotation={[1.32, 0, 0]}>
            <group position={[0, 143.07, 58.64]} rotation={[0.03, 0, 0]} />
            <group position={[0, 0, 77.5]}>
              <group position={[0, 0, -37.5]} rotation={[-Math.PI / 2, 0, 0]}>
                <group position={[-26.78, -31.11, -0.75]} rotation={[Math.PI / 2, -1.03, Math.PI / 2]}>
                  <group position={[0.68, -0.38, 4.96]} rotation={[0, 0, 0]}>
                    <group position={[-12.89, -9.61, -0.73]} rotation={[-1.24, 1.57, 0]}>
                      <group position={[2.42, -4.84, -0.01]} rotation={[-Math.PI, 1.31, Math.PI]}>
                        <group rotation={[1.33, 0, 0]}>
                          <group position={[0, -22.92, 0.03]} rotation={[0, 0, 0]}>
                            <group position={[0, 0, 0]} rotation={[1.29, 0, Math.PI]}>
                              <group position={[0.01, -11.29, 0.08]} rotation={[0, 0, 0]}>
                                <group position={[-0.01, -9.33, -0.08]} rotation={[0, 0, 0]}>
                                  <group position={[0, 0, 0]} rotation={[1.41, 0, 0]}>
                                    <mesh material={materials.material} geometry={nodes.R_P7_leg_0.geometry} />
                                  </group>
                                  <mesh material={materials.material} geometry={nodes.R_P6_G_leg_0.geometry} />
                                </group>
                                <mesh material={materials.material} geometry={nodes.R_P5_M_leg_0.geometry} />
                              </group>
                              <mesh material={materials.material} geometry={nodes.R_P4_leg_0.geometry} />
                            </group>
                            <mesh material={materials.material} geometry={nodes.R_P3_G_leg_0.geometry} />
                          </group>
                          <mesh material={materials.material} geometry={nodes.R_P2_leg_0.geometry} />
                        </group>
                        <mesh material={materials.material} geometry={nodes.R_P1_G_leg_0.geometry} />
                      </group>
                      <mesh material={materials.material} geometry={nodes.Drone_leg_R_leg_0.geometry} />
                    </group>
                    <mesh material={materials.body} geometry={nodes.Drone_Panel_R_body_0.geometry} />
                  </group>
                  <mesh material={materials.body} geometry={nodes['0'].geometry} />
                </group>
                <group position={[26.78, -31.11, -0.75]} rotation={[Math.PI / 2, 1.03, -Math.PI / 2]}>
                  <group position={[-0.68, -0.38, 4.96]} rotation={[0, 0, 0]}>
                    <group position={[12.89, -9.61, -0.73]} rotation={[-1.24, -1.57, 0]}>
                      <group position={[-2.42, -4.84, -0.01]} rotation={[Math.PI, -1.41, Math.PI]}>
                        <group rotation={[1.28, 0, 0]}>
                          <group position={[0, -22.92, 0.03]} rotation={[0, 0, 0]}>
                            <group position={[0, 0, 0]} rotation={[1.46, 0, -Math.PI]}>
                              <group position={[0.06, -11.24, 0.08]} rotation={[0, 0, -0.02]}>
                                <group position={[0.14, -9.37, -0.08]} rotation={[0, 0, 0]}>
                                  <group position={[0.01, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
                                    <mesh material={materials.material} geometry={nodes.L_P7_leg_0.geometry} />
                                  </group>
                                  <mesh material={materials.material} geometry={nodes.L_P6_G_leg_0.geometry} />
                                </group>
                                <mesh material={materials.material} geometry={nodes.L_P5_M_leg_0.geometry} />
                              </group>
                              <mesh material={materials.material} geometry={nodes.L_P4_leg_0.geometry} />
                            </group>
                            <mesh material={materials.material} geometry={nodes.L_P3_G_leg_0.geometry} />
                          </group>
                          <mesh material={materials.material} geometry={nodes.L_P2_leg_0.geometry} />
                        </group>
                        <mesh material={materials.material} geometry={nodes.L_P1_G_leg_0.geometry} />
                      </group>
                      <mesh material={materials.material} geometry={nodes.Drone_leg_L_leg_0.geometry} />
                    </group>
                    <mesh material={materials.body} geometry={nodes.Drone_Panel_L_body_0.geometry} />
                  </group>
                  <mesh material={materials.body} geometry={nodes.Drone_Gen_L_body_0.geometry} />
                </group>
                <group position={[-28.35, -10.2, 0.14]} rotation={[Math.PI / 2, -1.3, Math.PI / 2]}>
                  <mesh material={materials.body} geometry={nodes.Drone_UPanel_R_body_0.geometry} />
                </group>
                <group position={[28.23, -11.23, -0.08]} rotation={[Math.PI / 2, 1.3, -Math.PI / 2]}>
                  <mesh material={materials.body} geometry={nodes.Drone_UPanel_L_body_0.geometry} />
                </group>
                <group position={[0, 38.98, -3.07]}>
                  <mesh material={materials.body} geometry={nodes.Drone_UPart_body_0.geometry} />
                </group>
                <group position={[19.97, 24.56, -6.01]} rotation={[-1.68, -0.24, 1.57]}>
                  <group position={[0, -36.16, -10.97]} rotation={[-1.28, 1.07, Math.PI]}>
                    <mesh material={materials.body} geometry={nodes.Drone_Turb_Blade_L_body_0.geometry} />
                  </group>
                  <mesh material={materials.body} geometry={nodes.Drone_Turb_M_L_body_0.geometry} />
                </group>
                <group position={[-19.97, 24.56, -6.01]} rotation={[-1.69, 0.23, -Math.PI / 2]}>
                  <group position={[0, -36.16, -10.97]} rotation={[-1.28, -1.07, Math.PI]}>
                    <mesh material={materials.body} geometry={nodes.Drone_Turb_Blade_R_body_0.geometry} />
                  </group>
                  <mesh material={materials.body} geometry={nodes.Drone_Turb_M_R_body_0.geometry} />
                </group>
                <group position={[0, -38.68, 20.01]}>
                  <group position={[0.01, -5.51, -0.09]} rotation={[0, Math.PI / 2, 0]}>
                    <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0.09, -Math.PI / 2]}>
                      <group position={[0, -22.92, 0.03]} rotation={[0, 0, 0]}>
                        <group rotation={[1.22, 0, Math.PI]}>
                          <group position={[-0.02, -11.28, 0.08]} rotation={[0, 0, 0]}>
                            <group position={[0.01, -9.33, -0.08]} rotation={[0, 0, 0]}>
                              <group position={[0, 0, 0]} rotation={[1.26, 0, 0]}>
                                <mesh material={materials.material} geometry={nodes.F_P7_leg_0.geometry} />
                              </group>
                              <mesh material={materials.material} geometry={nodes.F_P6_G_leg_0.geometry} />
                            </group>
                            <mesh material={materials.material} geometry={nodes.F_P5_M_leg_0.geometry} />
                          </group>
                          <mesh material={materials.material} geometry={nodes.F_P4_leg_0.geometry} />
                        </group>
                        <mesh material={materials.material} geometry={nodes.F_P3_G_leg_0.geometry} />
                      </group>
                      <mesh material={materials.material} geometry={nodes.F_P2_leg_0.geometry} />
                    </group>
                    <mesh material={materials.material} geometry={nodes.F_P1_G_leg_0.geometry} />
                  </group>
                  <mesh material={materials.material} geometry={nodes.Drone_leg_F_leg_0.geometry} />
                </group>
                <group position={[0, -14.97, 41.51]}>
                  <group position={[0, -0.02, -8.91]} rotation={[3.12, 0.12, -3.14]}>
                    <mesh
                      name="1"
                      material={materials.body}
                      geometry={nodes['1'].geometry}
                      morphTargetDictionary={nodes['1'].morphTargetDictionary}
                      morphTargetInfluences={nodes['1'].morphTargetInfluences}
                    />
                  </group>
                  <mesh material={materials.body} geometry={nodes.Drone_ILens_body_0.geometry} />
                </group>
                <mesh material={materials.body} geometry={nodes.Drone_Body_body_0.geometry} />
              </group>
            </group>
          </group>
          <group position={[0, -99, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
            <mesh material={materials.Boden} geometry={nodes.Scheibe_Boden_0.geometry} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('Models/Drone/scene.gltf')
