/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'

export default function Model(props) {
  const group = useRef()
 
  const { nodes, materials } = useGLTF('/drone/drone.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[0,0,200]}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials.RubberSG} geometry={nodes.uploads_files_2493288_CGAXR_MC_Drone_High_OBJ_1.geometry} />
        <mesh
          material={materials.Glas_refSG}
          geometry={nodes.uploads_files_2493288_CGAXR_MC_Drone_High_OBJ_2.geometry}
        />
        <mesh
          material={materials.Frosted_GlassSG}
          geometry={nodes.uploads_files_2493288_CGAXR_MC_Drone_High_OBJ_3.geometry}
        />
        <mesh
          material={materials.AluminiumSG}
          geometry={nodes.uploads_files_2493288_CGAXR_MC_Drone_High_OBJ_4.geometry}
        />
        <mesh material={materials.CarRimSG} geometry={nodes.uploads_files_2493288_CGAXR_MC_Drone_High_OBJ_5.geometry} />
        <mesh
          material={materials.car_paint_Base_colorSG}
          geometry={nodes.uploads_files_2493288_CGAXR_MC_Drone_High_OBJ_6.geometry}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/drone/drone.gltf')
